title: Despliegue De Aplicaciones Web
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://iespsur.github.io/

aux_links:
  Repositorio en GitHub: https://github.com/IESPSUR/daweb


# Navigation
nav:
  - title: "Sección 1: SSH"
    url: /seccion-1-ssh
    children:
      - title: "Conexión remota y SSH"
        url: /seccion-1-ssh/conexion-remota-ssh

  - title: "Sección 2: Herramientas de despliegue"
    url: /seccion-2-herramientas
    children:
      - title: "Introducción a Docker para desarrolladores"
        url: /seccion-2-herramientas/introduccion-docker
      - title: "Ejecutando y gestionando contenedores"
        url: /seccion-2-herramientas/ejecutando-contenedores
      - title: "Gestión de imágenes"
        url: /seccion-2-herramientas/gestion-imagenes
      # Añadir el resto de las subsecciones de la sección 2 aquí

  - title: "Sección 3: Servidor Apache"
    url: /seccion-3-apache
    children:
      - title: "Servidor Apache"
        url: /seccion-3-apache/servidor-apache
      # Añadir más subsecciones si son necesarias

  - title: "Sección 4: Apache Tomcat"
    url: /seccion-4-tomcat
    children:
      - title: "Apache Tomcat"
        url: /seccion-4-tomcat/apache-tomcat
      # Añadir más subsecciones si son necesarias

  - title: "Sección 5: DNS"
    url: /seccion-5-dns
    children:
      - title: "Servicios de nombres de dominio"
        url: /seccion-5-dns/servicios-nombres-dominio
      # Añadir más subsecciones si son necesarias
